import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import NavbarPhone from "./components/NavbarPhone";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-max-screen h-max-screen md:overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Show NavbarPhone for small screens, Navbar for medium+ screens */}
        <div className="block md:hidden p-2 ">
          <NavbarPhone />
        </div>
        <div className="hidden md:block ">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
